# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# React Native usually needs use_frameworks! for Flipper and other dependencies
use_frameworks! :linkage => ENV['USE_FRAMEWORKS'] ? ENV['USE_FRAMEWORKS'].to_sym : :static

target 'live_location_tracker' do
  config = use_native_modules!
  
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Firebase pods with modular headers
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseFirestore', :modular_headers => true
  
  # If you need other Firebase services
  # pod 'FirebaseAuth'
  # pod 'FirebaseStorage'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Workaround for Firebase xcframework issues
    installer.pods_project.targets.each do |target|
      if target.name == 'FirebaseFirestore'
        target.build_configurations.each do |config|
          # Disable bitcode for Firebase (recommended)
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          
          # If you still have build issues, try these:
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
          config.build_settings['OTHER_CFLAGS'] = '-DFIRFirestore_VERSION=10.15.0'
        end
      end
    end
  end
end
